version: '3.9'

services:
  testdb:
    image: postgres:13.4-alpine
    restart: always
    container_name: integration-tests-prisma
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: 'testdb'
      POSTGRES_USER: 'prisma'
      POSTGRES_PASSWORD: 'prisma'


